# Sellery configuration file

# Serve files from this directory (Path must be absolute)
#   Use $WORKING_DIR to subsitute the current working directory
#   So, if you want to serve relative paths, use:
#     $WORKING_DIR/relative/path
#   Paths should NOT end with a '/'!
WEBROOT = '$WORKING_DIR'

# This is the SHA512 digest to check the password against
PASSWD_HASH = '034ff213a060a0888230c3934cfb1cb1f80ab3f211a114b713598efac2d1a68f8d3402c6b08ace2f3990c4c029351d1141cf47ebc378fc9a83a5dddda6e38a8c'

# Sessions stay valid this many seconds, if inactive. Default: 600 (=10 minutes)
SESSION_DURATION = 600

# The port the webserver runs on. Default: 443 (=https)
WEBSERVER_PORT = 443

# SSL key and certificate (you have to generate these yourself!)
SSL_KEY_FILE = 'key.pem'
SSL_CERT_FILE = 'cert.pem'

